AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: HelloWorldLambdaJava

Resources:

  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldJava
      Runtime: java11
      MemorySize: 512
      Timeout: 2
      Handler: book.EnvVarLambda::handler
      CodeUri: target/lambda.jar
      Environment:
        Variables:
          DATABASE_URL: my-database-url

  ContextLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloContext
      Runtime: java11
      MemorySize: 512
      Handler: book.ContextLambda::handler
      CodeUri: target/lambda.jar
